In [10]:
import tensorflow as tf
import pandas as pd
import numpy as np
import scipy.sparse as sp
import pymongo 

from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [16]:
from tqdm import tqdm

In [6]:
df = pd.read_excel("police_added.xlsx", index_col = 0) # index_col = 0 // no Unnamed:0 col

In [7]:
matrix_df = df.loc[:,"managementOffice":"university"]

In [8]:
matrix_df.head()

,managementOffice,seniorCenter,childCare,library,communityFacilities,playGround,restFacilities,kindergarten,communitySpace,bicycleShed,publicOffice,policeOffice,hospital,departmentStore,mall,park,elementarySchool,middleSchool,highSchool,university
0,1,1,0,0,0,1,0,0,0,1,0,0,1,0,1,1,1,1,1,0
1,1,1,0,0,0,1,0,0,0,1,1,0,1,0,1,1,1,1,1,1
2,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0
3,1,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,0
4,1,1,0,0,0,1,0,0,0,0,1,0,1,0,1,1,1,1,1,1

In [9]:
print('Number of rows and columns:',matrix_df.shape)

Number of rows and columns: (25354, 20)